name: Build Translator EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build EXE
      run: |
        pyinstaller --noconsole --onefile --icon=ikona.ico --name "Tlumacz_Multi_A6" main.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Gotowy_Program
        path: dist/Tlumacz_Multi_A6.exe
